### ISSUE TITLE
Data Structure need list

### ISSUE THREAD

**Issue by sinkyoungdeok** [19-1-skku-oss/2019-1-OSS-L2#20]
RBTree // implemented by sinkyoungdeok
BTree // implemented by sinkyoungdeok
Dequeue 
Digraph
graph
BinaryTree
Circular_linked_list

**Comment by ljw322** [comment]
RBTree // implemented by sinkyoungdeok
BTree // implemented by sinkyoungdeok
Dequeue//implemented by ljw322
Digraph
graph
BinaryTree
Circular_linked_list

**Comment by sinkyoungdeok** [comment]
RBTree // implemented by sinkyoungdeok
BTree // implemented by sinkyoungdeok
Dequeue//implemented by ljw322
Digraph //implemented by sinkyoungdeok
graph //implemented by sinkyoungdeok
BinaryTree
Circular_linked_list

**Comment by sinkyoungdeok** [comment]
RBTree // implemented by sinkyoungdeok
BTree // implemented by sinkyoungdeok
Dequeue//implemented by ljw322
Digraph //implemented by sinkyoungdeok
graph //implemented by sinkyoungdeok
BinaryTree
Circular_linked_list //implemented by sinkyoungdeok

**Comment by ljw322** [comment]
RBTree // implemented by sinkyoungdeok
BTree // implemented by sinkyoungdeok
Dequeue//implemented by ljw322
Digraph //implemented by sinkyoungdeok
graph //implemented by sinkyoungdeok
BinaryTree //implemented by ljw322
Circular_linked_list //implemented by sinkyoungdeok
