### ISSUE TITLE
함수이름 수정?

### ISSUE THREAD

**Issue by HongGildong98** [19-1-skku-oss/2019-1-OSS-L2#37]
commit highlight를 하면서 file 내부 함수관련해서 모았습니다.

신경덕
strspn : did you mean strcpn>?
comment highlight에는 원래 그대로 strspn으로 두었습니다. 
이지원
fipo : did you mean fibo?
comment highlight에는 fibo로 수정했습니다.

**Comment by sinkyoungdeok** [comment]
strspn이 맞아요 ~
