### ISSUE TITLE
code contribution highlight

### ISSUE THREAD

**Issue by sala0320** [19-1-skku-oss/2019-1-OSS-L2#39]
code contribution highlight이거랑 commit활동란이랑 머가 다른건가요??

**Comment by HongGildong98** [comment]
commit 은 그냥 파일이름만 나오기에 모든 커밋을 열어서 해당 파일에 어떤 부분이 주로 추가가되고 수정이 되었는지 확인한 후 따로 모아서 보인 것 입니다.

**Comment by HongGildong98** [comment]
같은 파일이이라도 계속 추가되고 삭제되기도 하니까 누가 주로 어떤 함수를 구현하거나 수정한 부분을 보이기 쉽게 하려했습니다.
